### ISSUE TITLE
hOCR flavour

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberry_runners#3]
@DiegoPino this continue the large post here https://github.com/esmero/format_strawberryfield/issues/11

**Comment by giancarlobi** [comment]
@DiegoPino Starting from tesseract (4.0.0) output I can generate this json:
``` json
{
    "page": "0 0 2481 3508",
    "words": [
        {
            "word": "Rapporto",
            "bbox": "1505 210 1674 251"
        },
        {
            "word": "tecnico",
            "bbox": "1688 210 1818 242"
        },
        {
            "word": "IRCrES,",
            "bbox": "1832 210 1973 242"
        },
        {
            "word": "6\/2018",
            "bbox": "1978 210 2124 247"
        },
```
by this code:
``` php
unset($hocr_output);
unset($hocr_array_output);
exec('tesseract /mnt/archicantadata/0c6/image-03.tiff stdout -l eng hocr', $hocr_output, $hocr_return);

$hocr_string_output = implode("", $hocr_output);
$hocr_string = str_replace('xmlns=', 'ns=', $hocr_string_output);
$xml = simplexml_load_string($hocr_string);
$body = $xml->body;

unset($hOCR);
//extract page boundary
$result = $xml->body->xpath("//div[@class='ocr_page']");
preg_match('/bbox\s[0-9]+\s[0-9]+\s[0-9]+\s[0-9]+/',$result[0]->attributes()['title'], $matches);
$hocr_page_bbox = str_replace('bbox ', '', $matches[0]);
$hOCR['page'] = $hocr_page_bbox;

//extract words and boundary
$result = $xml->body->xpath("//span[@class='ocrx_word']");
foreach ($result as $word) {
  $hocr_word = (string)$word[0];
  if ($hocr_word != ' ') {
    preg_match('/bbox\s[0-9]+\s[0-9]+\s[0-9]+\s[0-9]+/', $word->attributes()['title'], $matches);
    $hocr_word_bbox = str_replace('bbox ', '', $matches[0]);
    $hOCR['words'][] = array("word" => $hocr_word, "bbox" => $hocr_word_bbox);
  }
}
$hOCR_json = json_encode($hOCR, JSON_PRETTY_PRINT);
print_r($hOCR_json);
```
As you can see, json output could be modified as you prefer.
This output is to allow me to continue to experiment hocr flavour.

**Comment by DiegoPino** [comment]
Giancarlo, looks good. Now we need to test if that output, can be used, when ingested in Solr via our special documents there to highlight text. I feel we have been there already, so i have to recheck the old thread.
So all this logic needs to go into a plugin. I will work on that today, mostly abstracting all the possible needs a flavour processor can have. And also match some methods to allow our Flavour service consumers to have a way of reusing the json schema imposition we designed a few months ago. Good work!

**Comment by giancarlobi** [comment]
@DiegoPino I make now a pull with code in hocr script as for exif if this can help you

**Comment by DiegoPino** [comment]
Great! Yes, that will help me a lot

**Comment by giancarlobi** [comment]
here: https://github.com/esmero/strawberry_runners/commit/df612b91174741cf2180f097326cfd022c7e8cf2

**Comment by DiegoPino** [comment]
Yes. Tesseract is setup to use 4 cores i thing be default.

**Comment by DiegoPino** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1600

**Comment by DiegoPino** [comment]
Solved too!
