### ISSUE TITLE
HOCR per image page(s)

### ISSUE THREAD

**Issue by alliomeria** [esmero/strawberry_runners#44]
# What is needed?

Post processor option to generate HOCR per image page(s), to complement the existing Post processor OCR/HOCR against PDF files.

_Per @DiegoPino's notes and discussions:_ 
   -  Needs to incorporate correct page sequencing
   - Add for each Page (no collapsed data) an extra location of HOCR URL
   - Allow the OCR postprocessor to feed from a URL

This will be great to have @DiegoPino! 🤓

**Comment by patdunlavey** [comment]
I believe my [PR])https://github.com/esmero/strawberry_runners/pull/47) for ISSUE-46 (sorry for making a duplicate issue!), once it's solid and merged, will meet the "Needs to incorporate correct page sequencing" requirement.

Perhaps "Add for each Page (no collapsed data) an extra location of HOCR URL" is needed for bookreader search? Can you provide more explanation @DiegoPino ? If this helps make bookreader search work, I'm totally interested in working on it.

And I have no idea what "Allow the OCR postprocessor to feed from a URL" means. Sounds like a stretch goal to me?

**Comment by DiegoPino** [comment]
Resolved
