### ISSUE TITLE
Typo makes ALTO to Miniocr not working

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberry_runners#50]
https://github.com/esmero/strawberry_runners/blob/75d6b59d11e7088dc2b7f2fc9c410e7a90b3a536/src/Plugin/StrawberryRunnersPostProcessor/OcrPostProcessor.php#L724
I think we need 
`if (strlen(trim($child_node['CONTENT'] ?? "")) > 0) {`
to make it works right

**Comment by DiegoPino** [comment]
Fixed by wonderful @giancarlobi with https://github.com/esmero/strawberry_runners/commit/15df338b52f2d738f8c9e203c78df46a0cc6ebc7. Thanks!!
