### ISSUE TITLE
Fatal error when using NLP

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberry_runners#59]
When I have NLP processing enabled, I'm seeing this error:
```
bash-5.1# drush queue:run strawberryrunners_process_background --items-limit=1
 [error]  TypeError: http_build_query(): Argument #1 ($data) must be of type array, null given in http_build_query() (line 67 of /var/www/html/web/modules/contrib/strawberry_runners/src/Web64/Nlp/NlpClient.php) #0 /var/www/html/web/modules/contrib/strawberry_runners/src/Web64/Nlp/NlpClient.php(67): http_build_query(NULL)
#1 /var/www/html/web/modules/contrib/strawberry_runners/src/Web64/Nlp/NlpClient.php(52): Drupal\strawberry_runners\Web64\Nlp\NlpClient->post_call('/status', NULL, 2)
#2 /var/www/html/web/modules/contrib/strawberry_runners/src/Plugin/StrawberryRunnersPostProcessor/OcrPostProcessor.php(362): Drupal\strawberry_runners\Web64\Nlp\NlpClient->get_call('/status', NULL)
#3 /var/www/html/web/modules/contrib/strawberry_runners/src/Plugin/QueueWorker/AbstractPostProcessorQueueWorker.php(612): Drupal\strawberry_runners\Plugin\StrawberryRunnersPostProcessor\OcrPostProcessor->run(Object(stdClass), 1)
```
The problem seems to begin [here](https://github.com/esmero/strawberry_runners/blob/main/src/Plugin/StrawberryRunnersPostProcessor/OcrPostProcessor.php#L362), where the `$data` argument that is eventually fed into http_build_query [here](https://github.com/esmero/strawberry_runners/blob/0.4.0/src/Web64/Nlp/NlpClient.php#L67) is set to `NULL`.

This could be a PHP version thing, where previously `http_build_query` would not have complained?

Is this an appropriate fix?:
```
          'content' => is_array($params) && !empty($params) ? http_build_query($params) : "",
```

**Comment by DiegoPino** [comment]
@patdunlavey I have not seen this one before. Is this because OCR failed? Or because a setting is missing? Your fix makes sense but knowing what we are not passing (so maybe why even bother to call NLP would be nice)

**Comment by DiegoPino** [comment]
@patdunlavey ok checked the code, look here 👀 !


`::get_call` only will call  `return $this->post_call($path, $params, $retry);` IF GET failed...
If your NLP64 server working?
We can pass an empty [] array always since we are only calling for "status" endpoint that does not require any arguments if that works for you. But why is your NLP server not responding?

```
public function get_call($path, $params, $retry = 0) {
    $url = $this->api_url . $path;

    $retry++;

    if (!empty($params)) {
      $url .= '?' . http_build_query($params);
    }

    $result = @file_get_contents($url, FALSE);

    $response = isset($http_response_header) && isset($http_response_header[0])
      ? $this->isValidResponse($http_response_header[0]) : FALSE;
    if ($response && !empty($result)) {
      return json_decode($result, 1);
    }
    else {
      if ($retry >= static::MAX_RETRY_HOST) {
        return NULL;
      }
      $this->chooseHost();
     // HERE @patdunlavey !!
      return $this->post_call($path, $params, $retry);
    }
  }

  public function post_call($path, $params, $retry = 0) {
    $url = $this->api_url . $path;
    $retry++;
    if ($retry > static::MAX_RETRY_HOST) {
      return NULL;
    }
    $opts = [
      'http' =>
        [
          'method'  => 'POST',
          'header'  => 'Content-type: application/x-www-form-urlencoded',
          'content' => http_build_query($params),
        ],
    ];
    $context = stream_context_create($opts);
    $result = @file_get_contents($url, FALSE, $context);
    $response = isset($http_response_header) && isset($http_response_header[0])
      ? $this->isValidResponse($http_response_header[0]) : FALSE;
    if ($response && !empty($result)) {
      return json_decode($result, 1);
    }
    else {
      if ($retry >= static::MAX_RETRY_HOST) {
        return NULL;
      }
      $this->chooseHost();
      return $this->post_call($path, $params, $retry);
    }
  }

**Comment by DiegoPino** [comment]
docker logs -f esmero-nlp? 
@aksm did you built that container? Can you please check your local/what responses you are getting?
Code fix can be either on the caller @patdunlavey. Call with a [] instead or add a kill switch that checks if $parameters passed to POST are empty then no POST call should be done.

**Comment by DiegoPino** [comment]
@patdunlavey I checked esmero/esmero-nlp:1.0.1-RC2-arm64  and that one is responding but has no fasttext. Will check others

**Comment by DiegoPino** [comment]
@patdunlavey checked on a running server

curl http://esmero-nlp:6400/status
{"message":"NLP Server by web64.com - with fasttext addition by digitaldogsbody","missing_libraries":[],"polyglot_lang_models":{"LANG:de":"out of date","LANG:en":"out of date","LANG:es":"out of date","LANG:hi":"out of date","LANG:it":"out of date","LANG:pt":"out of date"},"web64":{"app":"nlpserver","documentation":"https://github.com/digitaldogsbody/nlpserver-fasttext/README.md","endpoints":["/status","/gensim/summarize","/polyglot/neighbours","/langid","/polyglot/entities","/polyglot/sentiment","/newspaper","/readability","/spacy/entities","/afinn","/fasttext"],"github":"https://github.com/digitaldogsbody/nlpserver-fasttext","last_modified":"2022-04-21","version":"1.0.2"}}
bash-5.1#

**Comment by DiegoPino** [comment]
@patdunlavey I leave the fix option to you. Since I can not change the signature of that class because I'm extending it (reason why nothing is `typed` in the arguments, sorry... probably adding code inside to not make any calls via POST if no arguments would make more sense?

**Comment by patdunlavey** [comment]
If I remove `/status` from the url, I get a NLP console web page. The `/status` url returns a 405 Method not allowed. So the server is running.

**Comment by DiegoPino** [comment]
Because I'm running the same server I'm clueless. I don't see that. You folks running some custom firewalls and stuff?

**Comment by aksm** [comment]
@DiegoPino No errors on my end from both local deployments and archipelago-deployment-live. No problems with curl and `/status` either.

**Comment by DiegoPino** [comment]
Tested both on arm64 and amd64 (Linux and Mac) and nope, all well too!
curl http://esmero-nlp:6400/status
{"message":"NLP Server by web64.com - with fasttext addition by digitaldogsbody","missing_libraries":[],"polyglot_lang_models":{"LANG:de":"out of date","LANG:en":"out of date","LANG:es":"out of date","LANG:hi":"out of date","LANG:it":"out of date","LANG:pt":"out of date"},"web64":{"app":"nlpserver","documentation":"https://github.com/digitaldogsbody/nlpserver-fasttext/README.md","endpoints":["/status","/gensim/summarize","/polyglot/neighbours","/langid","/polyglot/entities","/polyglot/sentiment","/newspaper","/readability","/spacy/entities","/afinn","/fasttext"],"github":"https://github.com/digitaldogsbody/nlpserver-fasttext","last_modified":"2022-04-21","version":"1.0.2"}}

**Comment by patdunlavey** [comment]
Thank you both. I'm clueless as to what the issue is, except that clearly it's not a problem upstream, so never mind about that! 

It does seem that passing NULL to the http_build_query function shouldn't happen in any case, so I'll send you a PR for that - thanks for the suggestions.

**Comment by patdunlavey** [comment]
PR Created: https://github.com/esmero/strawberry_runners/pull/60/files

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/strawberry_runners/commit/4f79d8ecf09504205b4c9e480b31c285dd852d3c by @patdunlavey
