### ISSUE TITLE
Sequence incorrect for OCR on multiple-image object

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberry_runners#65]
When using the method described [here](https://github.com/esmero/strawberryfield/pull/235#issuecomment-1299255316) to create a CreativeWorkSeries that is to be displayed using the book viewer with in-book searchable OCR'd text, I'm finding that if I attached more than one image file to one of the page objects, that the book viewer (correctly) displays the extra image file as an extra page, the extra image file is OCR'd and saved and indexed in solr, and the content of that page is searchable in the book viewer. However in-book searching does not find it on the correct page, and the highlight displays on the incorrect page. The smoking gun is, when looking in the key_value table, the name of the ocr record always sets the sequence number as 1. 

To answer your question @DiegoPino, the json for the page objects in question *do* have `sequence_id` values, and the file attachments do have correct `sequence` values (1, 2, 3 etc.).

I tried re-creating this page object with two image files, rather than first having one image file, saving, and then adding a second image file. No difference - the two images are saved in the key_value table with sequence number of 1.

I spent a while (without xdebug working on my local, alas) trying to isolate where the problem may be happening. The $sequence_number is correct in [line 311](https://github.com/esmero/strawberry_runners/blob/0.5.0/src/Plugin/StrawberryRunnersPostProcessor/OcrPostProcessor.php#L311) of the OcrPostProcessor. However, I noticed [here](https://github.com/esmero/strawberry_runners/blob/0.5.0/src/Plugin/QueueWorker/AbstractPostProcessorQueueWorker.php#L233-L235) of the AbstractPostProcessorQueueWorker, that it sets the $sequence_key to 1 if $data->siblings is not greater than one. And, I noticed in the `strawberryrunners_process_background` queue entries, that while the sequence value is correct, siblings is always set to 1. So that would force the sequence number to always be one.

So maybe this could be fixed by finding where the siblings value is being incorrectly set for multiple-file objects?

**Comment by DiegoPino** [comment]
@patdunlavey and copying @alliomeria here too.
The pull request merged does not cover the use case. The use case here is very hard to model without the extra logic I'm building in an alternate search endpoint that uses the Manifest as source to calculate the Pages.

let me explain: If you have the following:
ADO 1: One Image
ADO 2: Two Images (LAST IMAGE HERE CONTAINS THE WORD "PAT")
ADO 3: One Image 
ADO 4: Three Images (SECOND IMAGE HERE CONTAINS THE WORD "PAT")
ADO 5: One Image 

All Children of a CWS. If your use cases implies, any (all) images of any children will become a Page (a Canvas), the we have here 8 pages (8 Canvases). If I search FOR "PAT" I will find it in sequence_id (of the ADO) number 2. To know that I have to return the highlight in page (3) I have to count all images for sequence_id = 1, previous ones in sequence_id =2  and add an offset. now "PAT" also matches  sequence_id = 4. Means I have to calculate all previous images for ADO 1, ADO 2, ADO 3, AND first image of ADO 4, use that as offset, add to the Page number to return to IAB. 

Let's say I do that. I fix that number/logic. And now your use cases is "Skip" TIFFs, only show JPEGS? 

Said differently, the pull request merged assumes one image per page/standard SHOW all children ordered by sequence_id.

You noticed that the `$sequence_key to 1 if $data->siblings`. The reason for that is the `sequence_key` in an SBFlavor document is not relative to an ADO, but relative to the file that generated it (made for PDFs, where one file will generate multiple sequences) so does not apply for this case. Every Image is going to produce correctly, relative to itself (except for multi layer TIFFs, theory, have not even tested it) a sequence_key = 1. The `$sibilings` is not a value that tracks ADOs, but number of sequences a single file (PDF) will/could eventually generate. 


Ok, so back to the solution. I don't understand the use case yet (In the sense of making a book, I understand if you are building a complex CWS) or at least not as a common/simple one I can machine that covers any other further use case that might come out of it WITH the last pull.

But I'm working on the other search endpoint that parses the manifest itself to extract the sequence using some very heavy loading of files to check what/is/what. So don't give up!

**Comment by patdunlavey** [comment]
I should have said that I don't have a use case for this! It just occurred to me as an edge case to test because obviously it's easy to generate this case when an over-eager QC volunteer is manually creating content! I figured it was a bug, but since it's pretty complicated, and not a use-case that I know of, I'm happy to tag this as low priority, or perhaps make it a document-and-don't-fix task.

We do have cases where an ADO that is serving as a "page" in the "CWSBook" will have two files - one a medium-res jpeg and the other a high-res tiff (preservation master). That's a pretty common use-case, but one that can be handled with the strawberry runners setup.

**Comment by DiegoPino** [comment]
You can also skip the low rest jpeg in the manifest twig template itself or in the View that generates the list used for the CWS IIIF manifest V3 http://localhost:8001/admin/structure/views/view/data_creativeworks_series/edit/children_ispartof_canvas_rest

Happy you don't have the use case yet, but as promised, I'm working since last week on the smarter search that will use the manifest to decide + the IIIF Search API response version that can be used as search in Mirador and UV formatter.

Thanks @patdunlavey !

**Comment by DiegoPino** [comment]
@patdunlavey closing this issue bc the solution lies not here but in format_strawberryfield and strawberryfield
