### ISSUE TITLE
Entity ID typo for postprocess action and stray DS_Store file

### ISSUE THREAD

**Issue by aksm** [esmero/strawberry_runners#72]
# What?
Just a small typo here:

https://github.com/esmero/strawberry_runners/blob/dbac9cf07d910dcef3f26d115ced1d5bd774e377/src/Plugin/Action/StrawberryRunnersPostProcess.php#L19

and a stray `.DS_Store` file in the same folder.

**Comment by DiegoPino** [comment]
Resolved
