### ISSUE TITLE
Process VTT as fake X/Y (time mutation) MiniOCR

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberry_runners#87]
# What?

Time and memory are constructs and you can draw/paint the past to recall its original dimension. That is the gist

This will allow to re-use backed to allow IIIF time based annotations

@alliomeria for your conference presentation. Work already started.

**Comment by alliomeria** [comment]
Thank you Diego! 🧙‍♂️

**Comment by DiegoPino** [comment]
For VTT parsing I am using https://github.com/laracasts/transcriptions. Might make things easier/more stable than me trying to regular-expression my way through files. Only issue I see are SRTs... that are very close to a VTT but 
1.- Don't have a dash before the text
2.- Don't have a header/first line that says webVTT

**Comment by DiegoPino** [comment]
This is where the code goes... https://github.com/esmero/strawberry_runners/blob/b47220647cd493a12c4226f9ddef3478e06c3b34/src/Plugin/StrawberryRunnersPostProcessor/TextPostProcessor.php#L287

And this are the WebVTT specs

https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

One thing I wonder @alliomeria is we will require the Manifest itself to reference in VTT to allow a match ... or we will handle VTT for video as "it exists even if the manifest does not mention it"

**Comment by alliomeria** [comment]
Hmmm, that's a good question @DiegoPino...

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberry_runners/commit/298e6c444301e638ddeae0e4fcdd1274717e95e7
